services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - spring-postgres
      - pgadmin-bd
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres_db
    environment:
      - PGADMIN_DEFAULT_EMAIL=lol@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    networks:
      - pgadmin-bd
    ports:
      - "5050:80"
    restart: always

  app:
    build:
      context: ./demo
    depends_on:
      - postgres_db
    container_name: 'java-app-postgres'
    networks:
      - spring-postgres
    ports:
      - "8081:8080"

networks:
  spring-postgres:
  pgadmin-bd:
